### ISSUE TITLE
Question when using a second account

### ISSUE THREAD

**Issue by ypan887** [ddollar/heroku-accounts#75]
I have issue push to heroku using new accounts
I logged in as account 1, install this plugin and followed instruction, I then set up account 2
Running heroku accounts, I can see both accounts and new account is defaults
When I tried to push to heroku, it says I am using accounts 1 even thought I have set to account 2
I ran heroku logout and now I have to login one account at a time, the plugin is not working.

**Comment by enoughtoo** [comment]
I had this experience before. What I have noticed is that you have to "add account" at different repositories. i.e. if you have added account 1 at ../heroku-apps/account1, you have to move to ../heroku/app/account2, then set the account 2 there. Otherwise the keys and accounts information are messed up and you cannot use account 2 at all.

Hope that could help you.

**Comment by mfhholmes** [comment]
Same experience. Two accounts set up. Heroku accounts:whoami says account 2, but git push says account 1.
Heroku logout and login as account 2 fixes it, which is a workaround rather than a solution

**Comment by kurko** [comment]
https://github.com/ddollar/heroku-accounts/issues/83
